SupplyManagement-NET48/Models/Vendor.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace SupplyManagement_NET48.Models
{
    [Table("tb_m_vendors")]
    public class Vendor : BaseEntity
    {
        [Column("vendor_name", TypeName = "nvarchar(max)")]
        public string Name { get; set; }
        [Column("email", TypeName = "nvarchar")]
        public string Email { get; set; }
        [Column("phone_number", TypeName = "nvarchar")]
        public string PhoneNumber { get; set; }
        [Column("photo_profile", TypeName = "nvarchar(max)")]
        public string PhotoProfile { get; set; }
        [Column("sector", TypeName = "nvarchar")]
        public string Sector { get; set; }
        [Column("type", TypeName = "nvarchar")]
        public string Type { get; set; }
        [Column("is_admin_approve")]
        public bool IsAdminApprove { get; set; }
        [Column("is_manager_approve")]
        public bool IsManagerApprove { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

        // Cardinality
        public AccountVendor AccountVendor { get; set; }
        public ICollection<Project> Projects { get; set; }
    }
}

SupplyManagement-NET48/Controllers/VendorController.cs
using SupplyManagement_NET48.Models;
using SupplyManagement_NET48.Services;
using System;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web.Mvc;

namespace SupplyManagement_NET48.Controllers
{
    /*[Authorize]*/
    public class VendorController : Controller
    {
        private readonly VendorService _vendorService;
        public VendorController(VendorService vendorService)
        {
            _vendorService = vendorService;
        }

        // GET: Vendors
        public ActionResult Index()
        {
            var vendors = _vendorService.Get();
            var token = Request.Cookies["AuthToken"]?.Value;
            var handler = new JwtSecurityTokenHandler();
            if (token != null)
            {
                var jsonToken = handler.ReadToken(token) as JwtSecurityToken;

                var roleClaim = jsonToken.Claims.FirstOrDefault(claim => claim.Type == ClaimTypes.Role || claim.Type == "Role")?.Value;
                /*var fullName = jsonToken?.Payload["FullName"]?.ToString();*/

                ViewBag.UserRole = roleClaim;
                /*ViewBag.Fullname = fullName;*/
            }
            return View(vendors);
        }

        // GET: Vendors/Details/5
        public ActionResult Details(Guid id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var vendor = _vendorService.Get(id);
            if (vendor == null) return HttpNotFound();
            return View(vendor);
        }

        // GET: Vendors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vendors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Vendor vendorDtoCreate)
        {
            if (ModelState.IsValid)
            {
                string fileName = Path.GetFileNameWithoutExtension(vendorDtoCreate.ImageFile.FileName);
                string extension = Path.GetExtension(vendorDtoCreate.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                vendorDtoCreate.PhotoProfile = "~/Photo/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Photo/"), fileName);
                vendorDtoCreate.ImageFile.SaveAs(fileName);
                _vendorService.Create(vendorDtoCreate);
                return RedirectToAction("Index");
            }

            return View(vendorDtoCreate);
        }

        // GET: Vendors/Edit/5
        public ActionResult Edit(Guid id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var vendor = _vendorService.Get(id);
            Session["imgPath"] = vendor.PhotoProfile;
            if (vendor == null) return HttpNotFound();
            return View(vendor);
        }

        // POST: Vendors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Vendor vendorDtoUpdate)
        {
            if (ModelState.IsValid)
            {
                if (vendorDtoUpdate.ImageFile != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(vendorDtoUpdate.ImageFile.FileName);
                    string extension = Path.GetExtension(vendorDtoUpdate.ImageFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    string physicalPath = Path.Combine(Server.MapPath("~/Photo/"), fileName);
                    vendorDtoUpdate.ImageFile.SaveAs(physicalPath);
                    vendorDtoUpdate.PhotoProfile = "~/Photo/" + fileName;

                    var result = _vendorService.Update(vendorDtoUpdate);

                    string oldPath = Request.MapPath(Session["imgPath"].ToString());

                    if (result == 1)
                    {
                        if (System.IO.File.Exists(oldPath))
                        {
                            System.IO.File.Delete(oldPath);
                        }
                        return RedirectToAction("Index");
                    }
                    else if (result == 0)
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                        return View("Error");
                    }
                }
                else
                {
                    vendorDtoUpdate.PhotoProfile = Session["imgPath"].ToString();
                    var result = _vendorService.Update(vendorDtoUpdate);
                    if (result == 1)
                    {
                        return RedirectToAction("Index");
                    }
                    else if (result == 0)
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                        return View("Error");
                    }
                }

            }
            return View(vendorDtoUpdate);
        }

        // GET: Vendors/Delete/5
        public ActionResult Delete(Guid id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var vendor = _vendorService.Get(id);
            if (vendor == null) return HttpNotFound();
            return View(vendor);
        }

        // POST: Vendors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            var vendor = _vendorService.Get(id);
            string currentPath = Request.MapPath(vendor.PhotoProfile);
            var result = _vendorService.Delete(id);

            if (result == 1)
            {
                if (System.IO.File.Exists(currentPath))
                {
                    System.IO.File.Delete(currentPath);
                }
                return RedirectToAction("Index");
            }
            else if (result == 0)
            {
                return HttpNotFound();
            }
            else
            {
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult AdminApprove(Guid guid)
        {
            if (ModelState.IsValid)
            {
                var result = _vendorService.AdminApprove(guid);

                if (result == 1)
                {
                    return RedirectToAction("Index");
                }
                else if (result == 0)
                {
                    return HttpNotFound();
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult AdminReject(Guid guid)
        {
            if (ModelState.IsValid)
            {
                var result = _vendorService.AdminReject(guid);

                if (result == 1)
                {
                    return RedirectToAction("Index");
                }
                else if (result == 0)
                {
                    return HttpNotFound();
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult ManagerApprove(Guid guid)
        {
            if (ModelState.IsValid)
            {
                var result = _vendorService.ManagerApprove(guid);

                if (result == 1)
                {
                    return RedirectToAction("Index");
                }
                else if (result == 0)
                {
                    return HttpNotFound();
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult ManagerReject(Guid guid)
        {
            if (ModelState.IsValid)
            {
                var result = _vendorService.ManagerReject(guid);

                if (result == 1)
                {
                    return RedirectToAction("Index");
                }
                else if (result == 0)
                {
                    return HttpNotFound();
                }
            }
            return View();
        }

        /*protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }*/
    }
}

SupplyManagement-NET48/Views/Vendor/Create.cshtml
@model SupplyManagement_NET48.Models.Vendor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vendor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoProfile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhotoProfile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhotoProfile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SupplyManagement-NET48/Views/Vendor/Delete.cshtml
@model SupplyManagement_NET48.Models.Vendor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vendor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AccountVendor.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountVendor.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhotoProfile)
        </dt>

        <dd>
            <img src="@Url.Content(Model.PhotoProfile)" width="50" height="50" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sector)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sector)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAdminApprove)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAdminApprove)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsManagerApprove)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsManagerApprove)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SupplyManagement-NET48/Views/Vendor/Details.cshtml
@model SupplyManagement_NET48.Models.Vendor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vendor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhotoProfile)
        </dt>

        <dd>
            <img src="@Url.Content(Model.PhotoProfile)" width="50" height="50" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sector)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sector)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAdminApprove)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAdminApprove)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsManagerApprove)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsManagerApprove)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

SupplyManagement-NET48/Views/Vendor/Edit.cshtml
@model SupplyManagement_NET48.Models.Vendor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm(Html.BeginForm("Edit", "Vendor", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Vendor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Guid)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoProfile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content(Session["imgPath"].ToString())" width="80" height="50" />
                <input type="file" name="ImageFile" accept=".jpg,.jpeg,.png" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SupplyManagement-NET48/Views/Vendor/Index.cshtml
@model IEnumerable<SupplyManagement_NET48.Models.Vendor>

@{
    string userRole = ViewBag.UserRole;
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@if (userRole == "Admin")
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhotoProfile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sector)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>Admin Approve</th>
        <th>Manager Approve</th>
        <th></th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <img src="@Url.Content(item.PhotoProfile)" width="80" height="50" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sector)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @if (item.IsAdminApprove)
                    {
                        <span>Approved by Admin</span>
                    }
                    else
                    {
                        <span>Not Approved</span>
                    }
                </td>
                <td>
                    @if (item.IsManagerApprove)
                    {
                        <span>Approved by Manager</span>
                    }
                    else
                    {
                        <span>Not Approved</span>
                    }
                </td>
                <td>
                    @if (userRole == "Admin" || userRole == "Vendor")
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.Guid })
                    }
                    |
                    @Html.ActionLink("Details", "Details", new { id = item.Guid }) |
                    @if (userRole == "Admin")
                    {
                        @Html.ActionLink("Delete", "Delete", new { id = item.Guid })
                    }
                    @if (userRole == "Admin")
                    {
                        using (Html.BeginForm("AdminApprove", "Vendor", new { guid = item.Guid }, FormMethod.Post, new { @class = "d-inline-block" }))
                        {
                            <button type="submit" class="btn btn-sm btn-success m-1">Approve</button>
                        }
                        using (Html.BeginForm("AdminReject", "Vendor", new { guid = item.Guid }, FormMethod.Post, new { @class = "d-inline-block" }))
                        {
                            <button type="submit" class="btn btn-sm btn-danger m-1">Reject</button>
                        }
                    }
                    @if (userRole == "Manager" && item.IsAdminApprove)
                    {
                        using (Html.BeginForm("ManagerApprove", "Vendor", new { guid = item.Guid }, FormMethod.Post, new { @class = "d-inline-block" }))
                        {
                            <button type="submit" class="btn btn-sm btn-success m-1">Approve</button>
                        }
                        using (Html.BeginForm("ManagerReject", "Vendor", new { guid = item.Guid }, FormMethod.Post, new { @class = "d-inline-block" }))
                        {
                            <button type="submit" class="btn btn-sm btn-danger m-1">Reject</button>
                        }
                    }
                </td>
            </tr>
        }
    }
    else
    {
        <p>No data available.</p>
    }
</table>